controller:
  serviceType: LoadBalancer

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  additionalPlugins:
    - github

agent:
  enabled: true

rbac:
  create: true

serviceAccount:
  create: true
  name: jenkins

persistence:
  enabled: true
  storageClass: "gp3"
  size: 8Gi
