application:
  name: django-app
  project: default
  repoURL: https://github.com/yuriiavr/my-microservice-project.git
  targetRevision: main
  path: lesson-8-9/charts/django-app
  destinationServer: https://kubernetes.default.svc
  destinationNamespace: django

repository:
  enabled: true
  name: my-microservice-project
