apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.application.project }}
  source:
    repoURL: {{ .Values.application.repoURL }}
    targetRevision: {{ .Values.application.targetRevision }}
    path: {{ .Values.application.path }}
  destination:
    server: {{ .Values.application.destinationServer }}
    namespace: {{ .Values.application.destinationNamespace }}
  syncPolicy:
    # Автоматична синхронізація змін із Git.
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
