replicaCount: 2

image:
  repository: 123456789012.dkr.ecr.us-west-2.amazonaws.com/lesson-8-9-django
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  POSTGRES_DB: "myproject_db"
  POSTGRES_USER: "myproject_user"
  POSTGRES_PASSWORD: "myproject_pass"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  DJANGO_SECRET_KEY: "dev-insecure-secret-key-change-me-in-production"
  DJANGO_DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "*"
