global:
  domain: argocd.local

configs:
  params:
    server.insecure: true

server:
  service:
    type: LoadBalancer

redis-ha:
  enabled: false
controller:
  replicas: 1
repoServer:
  replicas: 1
applicationSet:
  replicas: 1
